# Generated by Django 2.2.5 on 2021-01-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('ltp', models.IntegerField(default=0)),
                ('upper_ckt', models.IntegerField(default=0)),
                ('lower_ckt', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='ltp',
        ),
        migrations.AlterField(
            model_name='trade',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order_structure.Trade_companies'),
        ),
    ]
